// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using agrokorm.Models.Db;

namespace agrokorm.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20220621111444_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("agrokorm.Models.Products.Configurations.MembraneConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("MembraneId")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembraneId");

                    b.ToTable("MembraneConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Черный",
                            Length = 50,
                            MembraneId = 1,
                            Price = "14370",
                            Type = "type 150",
                            Width = 14
                        },
                        new
                        {
                            Id = 2,
                            Color = "Черный",
                            Length = 50,
                            MembraneId = 2,
                            Price = "13014",
                            Type = "type 150",
                            Width = 12
                        },
                        new
                        {
                            Id = 3,
                            Color = "Черный",
                            Length = 50,
                            MembraneId = 2,
                            Price = "15186",
                            Type = "type 150",
                            Width = 14
                        },
                        new
                        {
                            Id = 4,
                            Color = "Черный",
                            Length = 50,
                            MembraneId = 2,
                            Price = "17922",
                            Type = "type 150",
                            Width = 16
                        },
                        new
                        {
                            Id = 5,
                            Color = "Черный",
                            Length = 50,
                            MembraneId = 2,
                            Price = "22692",
                            Type = "type 150",
                            Width = 18
                        },
                        new
                        {
                            Id = 6,
                            Color = "Черно-белый",
                            Length = 50,
                            MembraneId = 2,
                            Price = "17460",
                            Type = "type 150",
                            Width = 14
                        },
                        new
                        {
                            Id = 7,
                            Color = "Черно-белый",
                            Length = 50,
                            MembraneId = 2,
                            Price = "21540",
                            Type = "type 150",
                            Width = 16
                        },
                        new
                        {
                            Id = 8,
                            Color = "Черно-белый",
                            Length = 50,
                            MembraneId = 2,
                            Price = "29268",
                            Type = "type 150",
                            Width = 18
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.Membrane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("Lenght")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Membranes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Color = "Черная",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            IsVisible = true,
                            Lenght = 50,
                            Name = "Плёнка Silоfolie strong",
                            Price = "10092",
                            Type = "type 150",
                            Width = 10
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Color = "Черная",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            IsVisible = true,
                            Lenght = 50,
                            Name = "Плёнка Silоfolie",
                            Price = "12414",
                            Type = "type 150",
                            Width = 10
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.SunFlowerViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SunFlowerViewModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of(The Extremes of Good and Evil) by Cicero, written in 45 BC."
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.SunflowerSeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfProduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technology")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SunflowerSeeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-95 Элит",
                            PlaceOfProduction = "Россия",
                            Price = "10733",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-95 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "8401",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-26752 элит",
                            PlaceOfProduction = "Россия",
                            Price = "13647",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-26752 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9419",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-496 элит",
                            PlaceOfProduction = "Россия",
                            Price = "14413",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-496 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9660",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-498 элит",
                            PlaceOfProduction = "Россия",
                            Price = "14413",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-498 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9660",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-8003 элит",
                            PlaceOfProduction = "Россия",
                            Price = "14413",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-8003 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9660",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-8003 стандарт 1 мелк",
                            PlaceOfProduction = "Россия",
                            Price = "5660",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "Римисол элит",
                            PlaceOfProduction = "Россия",
                            Price = "13647",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "Римисол стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9507",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "Римисол стандарт 1 мелк",
                            PlaceOfProduction = "Россия",
                            Price = "5660",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-7806 элит",
                            PlaceOfProduction = "Россия",
                            Price = "13647",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-7806 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9507",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-6011 элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "8761",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-6011 элит 20",
                            PlaceOfProduction = "Россия",
                            Price = "9858",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-6011 стандарт 20",
                            PlaceOfProduction = "Россия",
                            Price = "7886",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-6011 стандарт 1 мелк 20",
                            PlaceOfProduction = "Россия",
                            Price = "5695",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-6013 элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "7886",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "Ягуар элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "9858",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "Ягуар станд 19",
                            PlaceOfProduction = "Россия",
                            Price = "7886",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "Аламо элит 20",
                            PlaceOfProduction = "Россия",
                            Price = "9858",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "Аламо стандарт 20",
                            PlaceOfProduction = "Россия",
                            Price = "7886",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-26752 элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "9858",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-26752 стандарт 19",
                            PlaceOfProduction = "Россия",
                            Price = "7886",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 6006 элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "11172",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 6006 стандарт 19",
                            PlaceOfProduction = "Россия",
                            Price = "8761",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 496 элит 20",
                            PlaceOfProduction = "Венгрия",
                            Price = "12047",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 496 элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "11172",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 496 стандарт 19",
                            PlaceOfProduction = "Россия",
                            Price = "8761",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 498 стандарт 20",
                            PlaceOfProduction = "Россия",
                            Price = "9419",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 6009 элит 2020",
                            PlaceOfProduction = "Венгрия",
                            Price = "9879",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 6009 элит 18",
                            PlaceOfProduction = "Россия",
                            Price = "8233",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.Configurations.MembraneConfiguration", b =>
                {
                    b.HasOne("agrokorm.Models.Products.Membrane", null)
                        .WithMany("membraneConfigurations")
                        .HasForeignKey("MembraneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("agrokorm.Models.Products.Membrane", b =>
                {
                    b.Navigation("membraneConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
