// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using agrokorm.Models.Db;

namespace agrokorm.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20220707075313_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("agrokorm.Models.Products.Configurations.MembraneConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("MembraneId")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MembraneId");

                    b.ToTable("MembraneConfigurations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Черный",
                            Length = 50,
                            MembraneId = 1,
                            Price = "14370",
                            Type = "type 150",
                            Width = 14
                        },
                        new
                        {
                            Id = 2,
                            Color = "Черный",
                            Length = 50,
                            MembraneId = 2,
                            Price = "13014",
                            Type = "type 150",
                            Width = 12
                        },
                        new
                        {
                            Id = 3,
                            Color = "Черный",
                            Length = 50,
                            MembraneId = 2,
                            Price = "15186",
                            Type = "type 150",
                            Width = 14
                        },
                        new
                        {
                            Id = 4,
                            Color = "Черный",
                            Length = 50,
                            MembraneId = 2,
                            Price = "17922",
                            Type = "type 150",
                            Width = 16
                        },
                        new
                        {
                            Id = 5,
                            Color = "Черный",
                            Length = 50,
                            MembraneId = 2,
                            Price = "22692",
                            Type = "type 150",
                            Width = 18
                        },
                        new
                        {
                            Id = 6,
                            Color = "Черно-белый",
                            Length = 50,
                            MembraneId = 2,
                            Price = "17460",
                            Type = "type 150",
                            Width = 14
                        },
                        new
                        {
                            Id = 7,
                            Color = "Черно-белый",
                            Length = 50,
                            MembraneId = 2,
                            Price = "21540",
                            Type = "type 150",
                            Width = 16
                        },
                        new
                        {
                            Id = 8,
                            Color = "Черно-белый",
                            Length = 50,
                            MembraneId = 2,
                            Price = "29268",
                            Type = "type 150",
                            Width = 18
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.GrassSeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Variety")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GrassSeeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Люцерна синяя",
                            Price = "450",
                            Variety = "Сирена ЭС, Артемида ЭС, Верко РС-1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Клевер луговой",
                            Price = "180, 240",
                            Variety = "Трио РС-1, ЭС"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Фестулолиум",
                            Price = "190",
                            Variety = "Вик 90 РС-1"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Фацелия",
                            Price = "220",
                            Variety = ""
                        },
                        new
                        {
                            Id = 5,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Эспарцет",
                            Price = "55",
                            Variety = "Песчаный 1251 РС-3"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Пайза",
                            Price = "50",
                            Variety = "Красава ЭС"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Кострец безостый",
                            Price = "220",
                            Variety = "Сибниисхоз 189 РС-1"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Райграс пастбищный",
                            Price = "170",
                            Variety = "Вик 66 РС-2"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Райграс однолетний",
                            Price = "120",
                            Variety = "Рапид"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Овсяница луговая",
                            Price = "170",
                            Variety = "Свердловская 37 РС-1"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Овсяница тростниковая",
                            Price = "190",
                            Variety = "Липальма"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Овсяница красная",
                            Price = "280",
                            Variety = "Бореал РС-2"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Тимофеевка луговая",
                            Price = "170",
                            Variety = "Ленинградская 204"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Тимофеевка",
                            Price = "170",
                            Variety = "Псковская местная РС-1"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Клевер полз. Белый",
                            Price = "750",
                            Variety = "РЕВЕНДЕЛ"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Мятлик луговой",
                            Price = "600",
                            Variety = "БАЛИН РС-1"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Ежа сборная",
                            Price = "180",
                            Variety = "Вик 61 РС-1"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Суданская трава",
                            Price = "50",
                            Variety = "Кинельская 100 РС-1"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Лядвенец рогатый",
                            Price = "договраня",
                            Variety = "Солнышко РС-1"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Однолетние и многолетние травы",
                            IsVisible = true,
                            Name = "Пырей ползучий",
                            Price = "140",
                            Variety = ""
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.Legumes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Variety")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Legumes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Вика яровая",
                            Price = "35",
                            Variety = "Никольская РС-2"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Горох посевной",
                            Price = "35, 40",
                            Variety = "Фараон РС-1, Софья ЭС"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Горох",
                            Price = "35, 40",
                            Variety = "Усатый кормовой РС-2"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Горох",
                            Price = "35",
                            Variety = "Пелюшка РСт"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Гречиха",
                            Price = "",
                            Variety = "Темп ЭС"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Вика / Овес 30/70",
                            Price = "23",
                            Variety = "Никольская РС-2/Скакун РС-1"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Горох/Овес 30/70",
                            Price = "23",
                            Variety = ""
                        },
                        new
                        {
                            Id = 8,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Горох/Овес 40/60",
                            Price = "24",
                            Variety = ""
                        },
                        new
                        {
                            Id = 9,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Вика/Горох/Овес 25/20/55",
                            Price = "25",
                            Variety = ""
                        },
                        new
                        {
                            Id = 10,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Овес",
                            Price = "17, 24",
                            Variety = "Скакун РС-1, ЭС"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Горчица белая",
                            Price = "40",
                            Variety = "Рапсодия РСт"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Соя",
                            Price = "",
                            Variety = "Мезенка РС-1"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Зерновые и зернобобовые культуры",
                            IsVisible = true,
                            Name = "Пшеница яровая",
                            Price = "25",
                            Variety = "Дарья РС-1"
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.Membrane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("Lenght")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Membranes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Черная",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            IsVisible = true,
                            Lenght = 50,
                            Name = "Плёнка Silоfolie strong",
                            Price = "10092",
                            Type = "type 150",
                            Width = 10
                        },
                        new
                        {
                            Id = 2,
                            Color = "Черная",
                            Description = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
                            IsVisible = true,
                            Lenght = 50,
                            Name = "Плёнка Silоfolie",
                            Price = "12414",
                            Type = "type 150",
                            Width = 10
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.SpringSeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpringSeeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Ячмень",
                            IsVisible = true,
                            Name = "Вакула ЭС",
                            Price = "29 р/кг"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Ячмень",
                            IsVisible = true,
                            Name = "Вакула PC1",
                            Price = "25 р/кг"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Ячмень",
                            IsVisible = true,
                            Name = "Приазовский 9 РС1",
                            Price = "25 р/кг"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Ячмень",
                            IsVisible = true,
                            Name = "Щедрый ЭС",
                            Price = "29 р/кг"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Ячмень",
                            IsVisible = true,
                            Name = "Космос ЭС",
                            Price = "29 р/кг"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Овес",
                            IsVisible = true,
                            Name = "Скакун ЭС",
                            Price = "29 р/кг"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Горох",
                            IsVisible = true,
                            Name = "Фокор ЭС",
                            Price = "42 р/кг"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Горох",
                            IsVisible = true,
                            Name = "Софья ЭС",
                            Price = "44 р/кг"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Гречиха",
                            IsVisible = true,
                            Name = "Девятка ЭС",
                            Price = "90 р/кг"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Гречиха",
                            IsVisible = true,
                            Name = "Темп ЭС",
                            Price = "90 р/кг"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Пшеница яровая",
                            IsVisible = true,
                            Name = "Дарья ЭС",
                            Price = "30 р/кг"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Пшеница яровая",
                            IsVisible = true,
                            Name = "Злата ЭС",
                            Price = "28 р/кг"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Пшеница яровая",
                            IsVisible = true,
                            Name = "Курьер ЭС",
                            Price = "28 р/кг"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Пшеница яровая",
                            IsVisible = true,
                            Name = "Ладья ЭС",
                            Price = "28 р/кг"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Пшеница яровая",
                            IsVisible = true,
                            Name = "Ласка ЭС",
                            Price = "28 р/кг"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Пшеница яровая",
                            IsVisible = true,
                            Name = "Радмира ЭС",
                            Price = "28 р/кг"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Лен масличный",
                            IsVisible = true,
                            Name = "ЛМ-98 ЭС",
                            Price = "160 р/кг"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Ячмень яровой",
                            IsVisible = true,
                            Name = "Космос ЭС",
                            Price = "30 р/кг"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Ячмень яровой",
                            IsVisible = true,
                            Name = "Нур ЭС",
                            Price = "28 р/кг"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Ячмень яровой",
                            IsVisible = true,
                            Name = "Надежный ЭС",
                            Price = "28 р/кг"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Ячмень яровой",
                            IsVisible = true,
                            Name = "Владимир ЭС",
                            Price = "28 р/кг"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Овес яровой",
                            IsVisible = true,
                            Name = "Кентер ЭС",
                            Price = "27 р/кг"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Соя",
                            IsVisible = true,
                            Name = "Виктория ЭС",
                            Price = "85 р/кг"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Сорта подсолнечника",
                            IsVisible = true,
                            Name = "Енисей Высокомасличный Ультраскороспелый",
                            Price = "100 р/кг"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Сорта подсолнечника",
                            IsVisible = true,
                            Name = "Казачий Высокомасличный Раннеспелый",
                            Price = "120 р/кг"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Сорта подсолнечника",
                            IsVisible = true,
                            Name = "Персей ЭС Высокомасличный Раннеспелый",
                            Price = "150 р/кг"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Сорта подсолнечника",
                            IsVisible = true,
                            Name = "Персей Супер Элита Высокомасличный Раннеспелый",
                            Price = "200 р/кг"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Гибриды кукурузы",
                            IsVisible = true,
                            Name = "Краснодарский 194 МВ Раннеспелый 90-99/190",
                            Price = "55 р/кг"
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.SunflowerSeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfProduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Technology")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SunflowerSeeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-95 Элит",
                            PlaceOfProduction = "Россия",
                            Price = "10733",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-95 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "8401",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-26752 элит",
                            PlaceOfProduction = "Россия",
                            Price = "13647",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-26752 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9419",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-496 элит",
                            PlaceOfProduction = "Россия",
                            Price = "14413",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-496 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9660",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-498 элит",
                            PlaceOfProduction = "Россия",
                            Price = "14413",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-498 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9660",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-8003 элит",
                            PlaceOfProduction = "Россия",
                            Price = "14413",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-8003 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9660",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-8003 стандарт 1 мелк",
                            PlaceOfProduction = "Россия",
                            Price = "5660",
                            Technology = "CУМО"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "Римисол элит",
                            PlaceOfProduction = "Россия",
                            Price = "13647",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "Римисол стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9507",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "Римисол стандарт 1 мелк",
                            PlaceOfProduction = "Россия",
                            Price = "5660",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-7806 элит",
                            PlaceOfProduction = "Россия",
                            Price = "13647",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Гибрид подсолнечника (урожай 2021 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-7806 стандарт",
                            PlaceOfProduction = "Россия",
                            Price = "9507",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-6011 элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "8761",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-6011 элит 20",
                            PlaceOfProduction = "Россия",
                            Price = "9858",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-6011 стандарт 20",
                            PlaceOfProduction = "Россия",
                            Price = "7886",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-6011 стандарт 1 мелк 20",
                            PlaceOfProduction = "Россия",
                            Price = "5695",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-6013 элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "7886",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "Ягуар элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "9858",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "Ягуар станд 19",
                            PlaceOfProduction = "Россия",
                            Price = "7886",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "Аламо элит 20",
                            PlaceOfProduction = "Россия",
                            Price = "9858",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "Аламо стандарт 20",
                            PlaceOfProduction = "Россия",
                            Price = "7886",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-26752 элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "9858",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС-Х-26752 стандарт 19",
                            PlaceOfProduction = "Россия",
                            Price = "7886",
                            Technology = "Классическая"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 6006 элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "11172",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 6006 стандарт 19",
                            PlaceOfProduction = "Россия",
                            Price = "8761",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 496 элит 20",
                            PlaceOfProduction = "Венгрия",
                            Price = "12047",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 496 элит 19",
                            PlaceOfProduction = "Россия",
                            Price = "11172",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 496 стандарт 19",
                            PlaceOfProduction = "Россия",
                            Price = "8761",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 498 стандарт 20",
                            PlaceOfProduction = "Россия",
                            Price = "9419",
                            Technology = "СУМО"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 6009 элит 2020",
                            PlaceOfProduction = "Венгрия",
                            Price = "9879",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Гибрид подсолнечника (урожай  2019- 2020 года) НС",
                            IsVisible = true,
                            Name = "НС Х 6009 элит 18",
                            PlaceOfProduction = "Россия",
                            Price = "8233",
                            Technology = "ЧИСТОЕ ПОЛЕ"
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.Szr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Analog")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consumption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfProduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Szrs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Analog = "",
                            Category = "Гербициды",
                            Consumption = "0.4-0.6",
                            Dv = "300 г/л 2,4-Д этилгексилового эфира и 6,25 г/л флорасулама",
                            IsVisible = true,
                            Manufacturer = "ФМРус",
                            Name = "Астерикс,СЭ",
                            PlaceOfProduction = "Китай",
                            Price = "1500"
                        },
                        new
                        {
                            Id = 2,
                            Analog = "",
                            Category = "Гербициды",
                            Consumption = "0.4-0.6",
                            Dv = "300 г/л 2,4-Д этилгексилового эфира и 6,25 г/л флорасулама",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Дисулам,СЭ",
                            PlaceOfProduction = "Китай",
                            Price = "1500"
                        },
                        new
                        {
                            Id = 3,
                            Analog = "",
                            Category = "Гербициды",
                            Consumption = "0.4-0.6",
                            Dv = "300 г/л 2,4-Д этилгексилового эфира и 6,25 г/л флорасулама",
                            IsVisible = true,
                            Manufacturer = "Агрокорм",
                            Name = "Опричник,СЭ",
                            PlaceOfProduction = "Китай",
                            Price = "1500"
                        },
                        new
                        {
                            Id = 4,
                            Analog = "",
                            Category = "Гербициды",
                            Consumption = "1.5-4",
                            Dv = "480 г/л бентазона",
                            IsVisible = true,
                            Manufacturer = "Ипрохим",
                            Name = "Гранбаз, ВР",
                            PlaceOfProduction = "",
                            Price = "2400"
                        },
                        new
                        {
                            Id = 5,
                            Analog = "Гранстар ПРО",
                            Category = "Гербициды",
                            Consumption = "0,015-0,025",
                            Dv = "750 г/кг трибенурон-метила",
                            IsVisible = true,
                            Manufacturer = "РосАгроХим",
                            Name = "Грэнери, ВДГ",
                            PlaceOfProduction = "Китай",
                            Price = "8500"
                        },
                        new
                        {
                            Id = 6,
                            Analog = "Гранстар ПРО",
                            Category = "Гербициды",
                            Consumption = "0,015-0,025",
                            Dv = "750 г/кг трибенурон-метила",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Гренадер, ВДГ",
                            PlaceOfProduction = "Китай",
                            Price = "8500"
                        },
                        new
                        {
                            Id = 7,
                            Analog = "Гранстар ПРО",
                            Category = "Гербициды",
                            Consumption = "0,015-0,025",
                            Dv = "750 г/кг трибенурон-метила",
                            IsVisible = true,
                            Manufacturer = "Ранголи",
                            Name = "Ранголи-Трибенурон, ВДГ",
                            PlaceOfProduction = "Китай",
                            Price = "8500"
                        },
                        new
                        {
                            Id = 8,
                            Analog = "Евро-Лайтинг",
                            Category = "Гербициды",
                            Consumption = "1-1.2",
                            Dv = "33 г/л  имазамокса +15 г/л имаза-пира",
                            IsVisible = true,
                            Manufacturer = "Гарант Оптима",
                            Name = "Евро-Ленд, ВРК",
                            PlaceOfProduction = "Венгрия",
                            Price = "3000"
                        },
                        new
                        {
                            Id = 9,
                            Analog = "Евро-Лайтинг",
                            Category = "Гербициды",
                            Consumption = "1-1.2",
                            Dv = "33 г/л  имазамокса +15 г/л имаза-пира",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Импекс Дуо, ВРК",
                            PlaceOfProduction = "Китай",
                            Price = "3000"
                        },
                        new
                        {
                            Id = 10,
                            Analog = "Лонтрел Гранд",
                            Category = "Гербициды",
                            Consumption = "0.12",
                            Dv = "750 г/кг клопиралида",
                            IsVisible = true,
                            Manufacturer = "РосАгроХим",
                            Name = "Клео, ВДГ",
                            PlaceOfProduction = "Китай",
                            Price = "9000"
                        },
                        new
                        {
                            Id = 11,
                            Analog = "",
                            Category = "Гербициды",
                            Consumption = "0,22-0,44",
                            Dv = "23 г/кг римсульфурон + 92г/кг ни-косульфурон + дикамба в виде диметиламинной соли (550 г/кг в пересчете на кислоту)",
                            IsVisible = true,
                            Manufacturer = "Картева",
                            Name = "Кордус Плюс, ВДГ",
                            PlaceOfProduction = "Китай",
                            Price = "11787"
                        },
                        new
                        {
                            Id = 12,
                            Analog = "Карибу",
                            Category = "Гербициды",
                            Consumption = "0.03",
                            Dv = "500 г/кг трифлусульфурон-метила",
                            IsVisible = true,
                            Manufacturer = "РосАгроХим",
                            Name = "Малибу, ВДГ",
                            PlaceOfProduction = "Россия",
                            Price = "22600"
                        },
                        new
                        {
                            Id = 13,
                            Analog = "Каллисто",
                            Category = "Гербициды",
                            Consumption = "0,15-0,25",
                            Dv = "480 г/л мезотриона",
                            IsVisible = true,
                            Manufacturer = "Союзагрохим",
                            Name = "Мезокорн, КС",
                            PlaceOfProduction = "Китай",
                            Price = "8000"
                        },
                        new
                        {
                            Id = 14,
                            Analog = "Инновейт",
                            Category = "Гербициды",
                            Consumption = "1-1,5",
                            Dv = "40 г/л никосульфурона",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Милафорт, КЭ ",
                            PlaceOfProduction = "Китай",
                            Price = "1300"
                        },
                        new
                        {
                            Id = 15,
                            Analog = "Инновейт",
                            Category = "Гербициды",
                            Consumption = "1-1,5",
                            Dv = "40 г/л никосульфурона",
                            IsVisible = true,
                            Manufacturer = "Гарант Оптима",
                            Name = "Милена, КЭ",
                            PlaceOfProduction = "Венгрия",
                            Price = "1300"
                        },
                        new
                        {
                            Id = 16,
                            Analog = "Инновейт",
                            Category = "Гербициды",
                            Consumption = "1-1,5",
                            Dv = "40 г/л никосульфурона",
                            IsVisible = true,
                            Manufacturer = "ХАМ",
                            Name = "Приоритет, КЭ",
                            PlaceOfProduction = "Китай",
                            Price = "1300"
                        },
                        new
                        {
                            Id = 17,
                            Analog = "",
                            Category = "Гербициды",
                            Consumption = "0,05-0,1",
                            Dv = "750 г/кг никосульфурона",
                            IsVisible = true,
                            Manufacturer = "РосАгроХим",
                            Name = "НЭО, ВДГ",
                            PlaceOfProduction = "Китай",
                            Price = "16800"
                        },
                        new
                        {
                            Id = 18,
                            Analog = "Элюмис",
                            Category = "Гербициды",
                            Consumption = "1,25-2",
                            Dv = "75 г / л мезотриона +  30 г / л ни-косульфурона",
                            IsVisible = true,
                            Manufacturer = "",
                            Name = "Легенда, МД",
                            PlaceOfProduction = "Китай",
                            Price = "2300"
                        },
                        new
                        {
                            Id = 19,
                            Analog = "Зеллек-супер",
                            Category = "Гербициды",
                            Consumption = "0,5-1",
                            Dv = "104 г/л галоксифоп-Р-метила",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Ореол, КЭ",
                            PlaceOfProduction = "Китай",
                            Price = "3000"
                        },
                        new
                        {
                            Id = 20,
                            Analog = "Зеллек-супер",
                            Category = "Гербициды",
                            Consumption = "0,5-1",
                            Dv = "104 г/л галоксифоп-Р-метила",
                            IsVisible = true,
                            Manufacturer = "Гарант Оптима",
                            Name = "Сокол, КЭ",
                            PlaceOfProduction = "Китай",
                            Price = "3000"
                        },
                        new
                        {
                            Id = 21,
                            Analog = "Пивот",
                            Category = "Гербициды",
                            Consumption = "0,50-0,8",
                            Dv = "100 г/л имазетапира",
                            IsVisible = true,
                            Manufacturer = "Гарант Оптима",
                            Name = "Серп, ВР",
                            PlaceOfProduction = "Венгрия",
                            Price = "2800"
                        },
                        new
                        {
                            Id = 22,
                            Analog = "Бетанал Экс-перт",
                            Category = "Гербициды",
                            Consumption = "1-3",
                            Dv = "112 г/л этофумезат + 91 г/л фенмедифам + 71 г/л десмедифам",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Синбетан Эксперт ОФ, КЭ",
                            PlaceOfProduction = "Китай",
                            Price = "2000"
                        },
                        new
                        {
                            Id = 23,
                            Analog = "Экспресс",
                            Category = "Гербициды",
                            Consumption = "0,015-0,05",
                            Dv = "750 г/кг трибенурон-метила",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Прометей, ВДГ ",
                            PlaceOfProduction = "Венгрия",
                            Price = "15000"
                        },
                        new
                        {
                            Id = 24,
                            Analog = "Титус, СТС",
                            Category = "Гербициды",
                            Consumption = "0,03-0,05",
                            Dv = "250 г/кг римсульфурона",
                            IsVisible = true,
                            Manufacturer = "Форвард",
                            Name = "Римус, ВДГ",
                            PlaceOfProduction = "Китай",
                            Price = "15000"
                        },
                        new
                        {
                            Id = 25,
                            Analog = "Хармони, СТС",
                            Category = "Гербициды",
                            Consumption = "0,006-0,025",
                            Dv = "750 г/кг тифенсульфурон-метила",
                            IsVisible = true,
                            Manufacturer = "РосАгроХим",
                            Name = "Тифи ВДГ",
                            PlaceOfProduction = "Китай",
                            Price = "19500"
                        },
                        new
                        {
                            Id = 26,
                            Analog = "",
                            Category = "Гербициды",
                            Consumption = "0,006-0,025",
                            Dv = "450 имазетапира + 150 хлоримурон-этила",
                            IsVisible = true,
                            Manufacturer = "Август",
                            Name = "Фабиан, ВДГ",
                            PlaceOfProduction = "Китай",
                            Price = "19500"
                        },
                        new
                        {
                            Id = 27,
                            Analog = "Пума 100",
                            Category = "Гербициды",
                            Consumption = "0,4-0,9",
                            Dv = "100 г/л феноксапроп-П-этила + 27 г/л антидота клоквинтосет-мексила",
                            IsVisible = true,
                            Manufacturer = "Гарант Оптима",
                            Name = "Ягуар Супер 100, КЭ ",
                            PlaceOfProduction = "Венгрия",
                            Price = "2000"
                        },
                        new
                        {
                            Id = 28,
                            Analog = "Фастак",
                            Category = "Инсектициды",
                            Consumption = "0,1-0,15",
                            Dv = "100 г/л альфа-циперметрина",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Атрикс, КЭ",
                            PlaceOfProduction = "Китай",
                            Price = "1400"
                        },
                        new
                        {
                            Id = 29,
                            Analog = "Фастак",
                            Category = "Инсектициды",
                            Consumption = "0,1-0,15",
                            Dv = "100 г/л альфа-циперметрина",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Атрикс, КЭ",
                            PlaceOfProduction = "Китай",
                            Price = "1400"
                        },
                        new
                        {
                            Id = 30,
                            Analog = "",
                            Category = "Инсектициды",
                            Consumption = "0,04-0,12",
                            Dv = "300 г/л имидаклоприда + 100 г/л лямбда-цигалотрина",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Канонир ДУО, ВРК",
                            PlaceOfProduction = "Китай",
                            Price = "5200"
                        },
                        new
                        {
                            Id = 31,
                            Analog = "",
                            Category = "Инсектициды",
                            Consumption = "0,5-1",
                            Dv = "500г/л хлорпирифос + 50г/л ци-перметрин",
                            IsVisible = true,
                            Manufacturer = "Гарант Оптима",
                            Name = "Шаман, КЭ",
                            PlaceOfProduction = "Венгрия",
                            Price = "2000"
                        },
                        new
                        {
                            Id = 32,
                            Analog = "",
                            Category = "Фунгициды",
                            Consumption = "0,5",
                            Dv = "500 г/л карбендозима",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Аксиома, КС",
                            PlaceOfProduction = "Китай",
                            Price = "1500"
                        },
                        new
                        {
                            Id = 33,
                            Analog = "",
                            Category = "Фунгициды",
                            Consumption = "0,3-1,5",
                            Dv = "500 г/л карбендозима",
                            IsVisible = true,
                            Manufacturer = "РосАгроХим",
                            Name = "Дерозал Евро, КС",
                            PlaceOfProduction = "Китай",
                            Price = "1500"
                        },
                        new
                        {
                            Id = 34,
                            Analog = "",
                            Category = "Фунгициды",
                            Consumption = "0,4-0,8",
                            Dv = "224г/л спироксамин + 148г/л тебуконазол + 53г/л протиоконазол",
                            IsVisible = true,
                            Manufacturer = "Байер",
                            Name = "Солигор, КЭ",
                            PlaceOfProduction = "",
                            Price = "2930"
                        },
                        new
                        {
                            Id = 35,
                            Analog = "Альто Супер",
                            Category = "Фунгициды",
                            Consumption = "0,4-0,5",
                            Dv = "250 г/л пропиконазола + 80г/л ци-проконазола",
                            IsVisible = true,
                            Manufacturer = "Гарант Оптима",
                            Name = "Виртуоз, КЭ",
                            PlaceOfProduction = "Китай",
                            Price = "4000"
                        },
                        new
                        {
                            Id = 36,
                            Analog = "Альто Супер",
                            Category = "Фунгициды",
                            Consumption = "0,4-0,5",
                            Dv = "250 г/л пропиконазола + 80г/л ци-проконазола",
                            IsVisible = true,
                            Manufacturer = "Гарант Оптима",
                            Name = "Виртуоз, КЭ",
                            PlaceOfProduction = "Китай",
                            Price = "4000"
                        },
                        new
                        {
                            Id = 37,
                            Analog = "Альто Супер",
                            Category = "Фунгициды",
                            Consumption = "0,4-0,5",
                            Dv = "250 г/л пропиконазола + 80г/л ци-проконазола",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Фунгисил, КЭ",
                            PlaceOfProduction = "Китай",
                            Price = "3200"
                        },
                        new
                        {
                            Id = 38,
                            Analog = "",
                            Category = "Протравители",
                            Consumption = "0,5-0,8",
                            Dv = "92г/л дифеноконазол  + 23г/л ме-феноксам ",
                            IsVisible = true,
                            Manufacturer = "Сингента",
                            Name = "Дивиденд Экстрим, КС",
                            PlaceOfProduction = "",
                            Price = "3100"
                        },
                        new
                        {
                            Id = 39,
                            Analog = "Круйзер",
                            Category = "Протравители",
                            Consumption = "0,5-1",
                            Dv = "350 г/л тиаметоксам ",
                            IsVisible = true,
                            Manufacturer = "РосАгроХим",
                            Name = "Тиара, КС",
                            PlaceOfProduction = "Китай",
                            Price = "3500"
                        },
                        new
                        {
                            Id = 40,
                            Analog = "",
                            Category = "Протравители",
                            Consumption = "0,4-0,5",
                            Dv = "60 г/л тебуконазола +80 г/л  тиа-бендазола +60 г/л имазалила",
                            IsVisible = true,
                            Manufacturer = "РосАгроХим",
                            Name = "Стингер Трио, КС",
                            PlaceOfProduction = "Китай",
                            Price = "2800"
                        },
                        new
                        {
                            Id = 41,
                            Analog = "",
                            Category = "Протравители",
                            Consumption = "0,2-0,3",
                            Dv = "100г/лазоксистробин + 120г/л те-буконазол + 40г/л ципроконазол",
                            IsVisible = true,
                            Manufacturer = "Агрохим 21",
                            Name = "Триагро, КС",
                            PlaceOfProduction = "Китай",
                            Price = "3900"
                        },
                        new
                        {
                            Id = 42,
                            Analog = "",
                            Category = "Протравители",
                            Consumption = "0,2-0,25",
                            Dv = "60 г/л тиабендазол + 60 г/л тебу-коназол + 40 г/л имазалил",
                            IsVisible = true,
                            Manufacturer = "Гарант Оптима",
                            Name = "Тритон ,КС",
                            PlaceOfProduction = "Китай",
                            Price = "3500"
                        },
                        new
                        {
                            Id = 43,
                            Analog = "Реглон Супер",
                            Category = "Протравители",
                            Consumption = "2",
                            Dv = "150 г/л диквата (дибромид)",
                            IsVisible = true,
                            Manufacturer = "РосАгроХим",
                            Name = "Десикант Экспертоф, ВР",
                            PlaceOfProduction = "Китай",
                            Price = "1500"
                        },
                        new
                        {
                            Id = 44,
                            Analog = "Реглон Супер",
                            Category = "Протравители",
                            Consumption = "2",
                            Dv = "150 г/л диквата (дибромид)",
                            IsVisible = true,
                            Manufacturer = "АХТ",
                            Name = "Регистан, ВР",
                            PlaceOfProduction = "Китай",
                            Price = "1500"
                        });
                });

            modelBuilder.Entity("agrokorm.Models.Products.Configurations.MembraneConfiguration", b =>
                {
                    b.HasOne("agrokorm.Models.Products.Membrane", null)
                        .WithMany("MembraneConfigurations")
                        .HasForeignKey("MembraneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("agrokorm.Models.Products.Membrane", b =>
                {
                    b.Navigation("MembraneConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
